### ISSUE TITLE
Move hs._asm.undocumented.touchdevice into own repo

### ISSUE THREAD

**Issue by latenitefilms** [asmagill/hammerspoon_asm.undocumented#12]
@asmagill - Any chance you could please move `hs._asm.undocumented.touchdevice` into its own repo and update it so that it's co-routine friendly?

**Comment by asmagill** [comment]
Done.

I have verified it compiles and cleaned up a few warnings, but I haven't tested it very much, so let me know if it gives you any trouble.

**Comment by latenitefilms** [comment]
Legend, thank you! Will let you know how I get along.
