### ISSUE TITLE
make install: internal.m:3:9: fatal error: 'lauxlib.h' file not found

### ISSUE THREAD

**Issue by srustamo** [asmagill/hammerspoon_asm.undocumented#2]
What could be the reason for this error when running `make install`:
`internal.m:3:9: fatal error: 'lauxlib.h' file not found`

OS X 10.9.5

**Comment by asmagill** [comment]
Are you using Hammerspoon or Mjolnir?

In either case, you will need to have Lua installed via some mechanism... I use Homebrew, but Fink or MacPorts should work as well.

For Hammerspoon, you should install Lua 5.3

For Mjolnir, you'll need Lua 5.2

If you're using Hammerspoon, you could also do the following (this does not require the separate installation of Lua as described above):

sudo ln -s /Applications/Hammerspoon.app/Contents/Frameworks/LuaSkin.framework /Library/Frameworks/LuaSkin.framework

and then replace the #include "lauxlib.h" with #import <LuaSkin/LuaSkin.h>... this is actually the direction we're moving Hammerspoon in, but it still needs documenting and some older repositories (as you see!) still need updating.

**Comment by srustamo** [comment]
Installing lua with homebrew solved the issue.
