### ISSUE TITLE
displays with separate spaces

### ISSUE THREAD

**Issue by szymonkaliski** [asmagill/hammerspoon_asm.undocumented#4]
Any chance of possible getting space counts for each display, not just in total?

**Comment by asmagill** [comment]
I'm looking into some additions, and I think that should be doable.

**Comment by szymonkaliski** [comment]
Awesome! I've seen you already added `screensHaveSeparateSpaces`, cool! Ideally I'd love to get spaces count for each screen :)

**Comment by asmagill** [comment]
Check out the newest release... it's a complete re-write with a _LOT_ of new functions.  Getting the space count for each monitor should be easy to do with `hs._asm.undocumented.spaces.s.spacesByScreenUUID`.

**Comment by szymonkaliski** [comment]
thank you, great work :+1:
