### ISSUE TITLE
/bin/sh: luac-5.3: command not found

### ISSUE THREAD

**Issue by MichelDiz** [asmagill/hammerspoon_asm.undocumented#6]
make install       
luac-5.3 -p init.lua && echo "Passed"
/bin/sh: luac-5.3: command not found
make: *** [verify] Error 127

Also tried this https://stackoverflow.com/questions/5496003/how-do-i-install-lua-on-macos

**Comment by szymonkaliski** [comment]
@MichelDiz you don't have lua 5.3 installed, easiest would be with [homebrew](https://brew.sh) I think: `brew install lua@5.3`
